### ISSUE TITLE
Not able to create Superuser on your git version

### ISSUE THREAD

**Issue by twinbroskalaisrini** [deligence-vinit/django-appointments#1]
getting an error **TypeError: create_superuser() missing 1 required positional argument: 'username'**
while creating a Superuser from backend using cmd prompt "python manage.py superuser"

Thanks,
Kalaiarasan
twinbros.ece@gmail.com

**Comment by intrepidclass** [comment]
I ran into the same issue. 

This project uses a custom user model. In that model, the username field is set to None. So it doesn't exist anymore. The createsuperuser command does not seem built to handle this scenario.

What you can do is comment out the following lines in ../django-appointments/user/models.py:

`    #username = None
    #USERNAME_FIELD = 'email'
    #REQUIRED_FIELDS = []

`

Then create a superuser. And then uncommenting at least the bottom two lines (of the three mentioned above) again.
