### ISSUE TITLE
no such table: User - after applying default migrations 

### ISSUE THREAD

**Issue by maxiller** [deligence-vinit/django-appointments#2]
After setting up demo project from the repo and applying migrations, I'm unable to create superuser.

Exception thrown: 

> no such table: User

**Comment by intrepidclass** [comment]
Same here

**Comment by intrepidclass** [comment]
Running

`python manage.py makemigrations user
`
`python manage.py makemigrations hospital
`
`python manage.py makemigrations doctor
`
`python manage.py makemigrations patient
`
`python manage.py migrate
`

And then migrating

`python manage.py migrate
`

Solves this issue.
But then there's still the other issue that's open: issue #1 

(you may need to throw away your existing sqlite file for this to work)

**Comment by intrepidclass** [comment]
And:

`pip install django-crispy-forms`
